[[plugins]]
repo = 'Shougo/vimproc'
build = "make"

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vim-unite-giti']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "Shougo/neoyank.vim"

[[plugins]]
repo = "Shougo/unite-outline"

[[plugins]]
repo = 'vim-scripts/surround.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'hotchpotch/perldoc-vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo ='itchyny/vim-cursorword'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = "osyo-manga/unite-quickfix"

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
