[[plugins]]
repo = 'Shougo/vimproc.vim'
om_cmd = ['QuickRun']

[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_map = ['<C-p>']

[[plugins]]
repo = 'tacahiroy/ctrlp-funky'
on_map = ['<C-p>']
